on:
  workflow_dispatch: {}

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: 14
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.CLIPTUBE_UPLOADER_CREDENTIALS }}
    - name: install
      run: npm ci
    - name: build
      run: npm run build:macos
    - name: upload to Azure
      uses: azure/CLI@v1
      with:
        azcliversion: 2.22.1
        inlineScript: |
          az storage blob upload --account-name cliptube -c bin -n install.sh -f install.sh
          az storage blob upload --account-name cliptube -c bin -n cliptube-macos-x64 -f out/bin/cliptube-macos-x64
    - run: az logout
